### ISSUE TITLE
Question Regarding Point Calculation and Feature Request for Point Range Selection

### ISSUE THREAD

**Issue by NewsBee13** [Widiskel/moonbix-bot#1]
Hi,

I have a question regarding the point calculation in the game. I noticed that the output from the https://www.binance.com/bapi/growth/v1/friendly/growth-paas/mini-app-activity/third-party/game/start API returns various configurations for each game session, as seen in the example below:

{
    "code": "000000",
    "message": null,
    "messageDetail": null,
    "data": {
        "gameTag": "xxxxxxx",
        "specialRewardId": null,
        "cryptoMinerConfig": {
            "gameDuration": null,
            "hookSwipeSpeed": 300,
            "finalHookSwipeSpeed": 500,
            "itemSettingList": [
                {
                    "type": "REWARD",
                    "speed": 150,
                    "size": 50,
                    "quantity": 3,
                    "rewardValueList": [25, 25, 25]
                },
                {
                    "type": "TRAP",
                    "speed": 100,
                    "size": 50,
                    "quantity": 1,
                    "rewardValueList": [-20]
                },
                {
                    "type": "TRAP",
                    "speed": 150,
                    "size": 30,
                    "quantity": 2,
                    "rewardValueList": [-10, -10]
                },
                {
                    "type": "BONUS",
                    "speed": 80,
                    "size": 60,
                    "quantity": 1,
                    "rewardValueList": [60]
                },
                {
                    "type": "REWARD",
                    "speed": 100,
                    "size": 70,
                    "quantity": 2,
                    "rewardValueList": [50, 50]
                },
                {
                    "type": "REWARD",
                    "speed": 200,
                    "size": 30,
                    "quantity": 5,
                    "rewardValueList": [10, 10, 10, 10, 10]
                }
            ]
        }
    },
    "success": true
}

My concern is whether the points submitted after completing the game are accurately calculated based on the item settings (rewardValueList, trap, and bonus). I want to ensure that there is no discrepancy that could potentially be flagged later on.

Additionally, would it be possible to implement a feature where we can select a range for the total points to be submitted after completing the game? This would provide more control over the randomness of the point allocation and ensure it falls within a specific range.

Thank you for your assistance!

**Comment by Widiskel** [comment]
my point callculation is based on that response, but im avoid trap so im just calculate based on the reward , each hit give different `itemSettingList` especially in bonus part thats why the point is different for each hit. it not randomize but im calculate based on the `cryptoMinerConfig`

**Comment by NewsBee13** [comment]
aight well i got 325 point like in a row, and it get my account banned bro, thabksfully its not my main acc

**Comment by Widiskel** [comment]
> aight well i got 325 point like in a row, and it get my account banned bro, thabksfully its not my main acc

that not something that make your account banned, my 20 account still safe with around 50k point each
